
/*ROWSTORE VS COLUMNSTORE INDEX*/
--CLOUMN STORE INDEX ON THE TABLE FactResellerSales_HP S
SELECT 
  P.ENGLISHPRODUCTNAME AS ProductName,
  SUM(S.SALESAMOUNT) AS TotalSales
FROM 
FactResellerSales_HP S
JOIN DIMPRODUCT P
ON S.PRODUCTKEY = P.PRODUCTKEY
GROUP BY P.ENGLISHPRODUCTNAME

CREATE CLUSTERED COLUMNSTORE INDEX IDX_FACT_RESELLER_SALESHP
ON FACTRESELLERSALES_HP;

--ROW STORE INDEX ON THE SAME TABLE FactResellerSales_HP S: 

SELECT 
  P.ENGLISHPRODUCTNAME AS ProductName,
  SUM(S.SALESAMOUNT) AS TotalSales
FROM 
FactResellerSales S
JOIN DIMPRODUCT P
ON S.PRODUCTKEY = P.PRODUCTKEY
GROUP BY P.ENGLISHPRODUCTNAME


--EXECUTION PLAN FOR NON CLUSTERED INDEX
--THIS USE INDEX SEEK : BEST

--GIVEN QUERY COST UNDER NON CLUSTERED INDEX 
--Query 1: Query cost (relative to the batch): 4%
CREATE NONCLUSTERED INDEX IDX_FACT_RESELLER_SALES_CTN
ON FactResellerSales (CarrierTrackingNumber);

--FOR THE SAME QUERY WHEN YOU CREATE A NON CLUSTERED INDEX THEN THE EXECUTION PLAN WILL CHANGE COMPLETELY

SELECT * FROM 
FactResellerSales
WHERE CarrierTrackingNumber = '4911-403C-98';
--Actual number of rows read in clustered index :12
--all this information comes from the EXECUTION PLAN

--SAME QUERY AS ABOVE EXECUTED WITH HEAP :
--GIVEN QUERY COST FOR THE HEAP STRUCTURE Query 2: Query cost (relative to the batch): 96%

SELECT * FROM 
FactResellerSales_HP --TABLE FOR WHICH NO INDEX IS CREATED THUS HEAP
WHERE CarrierTrackingNumber = '4911-403C-98';

--Actual number of rows read in heap :60855
--all this information comes from the EXECUTION PLAN



------------------------------------------------------------------------------------------
--EXECUTION PLAN FOR THE CLUSTERED--
--USES THE INDEX SCAN: GOOD

SELECT *
FROM FactResellerSales
order by SalesOrderNumber;/*TIME FOR THE EXECUTION OF SORTING IN THETHE CLUSTERED 
IS LESSER BECAUSE OF THE FACT THAT ALL THE DATA IN THE CLUSTERED INDEX
IS ALREDY SORTED*/



-----------------------------------------------------------------------------------
-- EXECUTION PLAN FOR THE HEAP 
-- USES THE FULL TABLE SCAN : WORST AMONT THE 3 

SELECT *
FROM FactResellerSales_HP
ORDER BY SalesOrderNumber;/*THIS TAKES MORE TIME BECAUSE IT NEEDS TO CREATE
AN ADDITIONAL STEP FOR SORTING OUT THE DATA*/