--EXECUTION PLAN FOR THE CLUSTERED--

SELECT *
FROM FactResellerSales
order by SalesOrderNumber;/*TIME FOR THE EXECUTION OF SORTING IN THETHE CLUSTERED 
IS LESSER BECAUSE OF THE FACT THAT ALL THE DATA IN THE CLUSTERED INDEX
IS ALREDY SORTED*/

-- EXECUTION PLAN FOR THE HEAP 

SELECT *
FROM FactResellerSales_HP
ORDER BY SalesOrderNumber;/*THIS TAKES MORE TIME BECAUSE IT NEEDS TO CREATE
AN ADDITIONAL STEP FOR SORTING OUT THE DATA*/