--heap structure
SELECT * 
INTO FACT_INTERNETSALES_HP
FROM FactInternetSales

--SPACE OCCUPIED FOR THE HEAP INDEX TABLES
--DATA SPACE : 9.633 MB
--INDEX SPACE : 0.008 MB


--CLUSTERED ROWSTORE INDEX 

--CREATED A COPY OF THE TABLE FactInternetSales FOR CREATING ROWSTORE INDEX 
SELECT * 
INTO FACT_INTERNETSALES_RS
FROM FactInternetSales;

--SPACE OCCUPIED FOR THE ROWSTORE INDEX TABLES
--DATA SPACE : 9.633 MB
--INDEX SPACE : 0.055 MB

CREATE CLUSTERED INDEX IDX_FACTINTERNETSALES_RS 
ON FACT_INTERNETSALES_RS (SalesOrderNumber,SalesOrderLineNumber)


--CLUSTERED COLUMNSTORE INDEX

SELECT * 
INTO FACT_INTERNETSALES_CS
FROM FactInternetSales;

--SAPCE OCCUPIED FOR THE COLUMNSTORE INDEX TABLES
--DATA SPACE : 1.461 MB
--INDEX SPACE : 0.000 MB

CREATE CLUSTERED COLUMNSTORE INDEX IDX_FACTINTERNETSALES_CS 
ON FACT_INTERNETSALES_CS


